from app.database import SessionLocal
from app.models.category import Category
from app.models.policy import Policy
from app.models.stats import Stats

CATEGORIES = [
    {"slug": "infrastruktur", "name": "Infrastruktur", "description": "Jalan, jembatan, air bersih, dan fasilitas publik", "icon": "infrastruktur"},
    {"slug": "pendidikan", "name": "Pendidikan", "description": "Sekolah, beasiswa, dan kurikulum daerah", "icon": "pendidikan"},
    {"slug": "kesehatan", "name": "Kesehatan", "description": "Puskesmas, BPJS, dan program kesehatan ibu dan anak", "icon": "kesehatan"},
    {"slug": "lingkungan-hidup", "name": "Lingkungan Hidup", "description": "Hutan, sungai, limbah, dan konservasi alam", "icon": "lingkungan-hidup"},
    {"slug": "ekonomi-umkm", "name": "Ekonomi & UMKM", "description": "Usaha kecil, perizinan, pasar, dan investasi", "icon": "ekonomi-umkm"},
    {"slug": "pertanian-perikanan", "name": "Pertanian & Perikanan", "description": "Nelayan, petani, penyuluhan, dan hasil bumi", "icon": "pertanian-perikanan"},
    {"slug": "adat-budaya", "name": "Adat & Budaya", "description": "Hak ulayat, seni budaya, dan perlindungan adat", "icon": "adat-budaya"},
    {"slug": "pariwisata", "name": "Pariwisata", "description": "Destinasi wisata, promosi, dan infrastruktur pariwisata", "icon": "pariwisata"},
    {"slug": "tata-ruang", "name": "Tata Ruang", "description": "RTRW, izin bangunan, dan perencanaan wilayah", "icon": "tata-ruang"},
    {"slug": "hukum-peraturan", "name": "Hukum & Peraturan", "description": "Regulasi umum, ketertiban, dan pemerintahan", "icon": "hukum-peraturan"},
]

POLICIES = [
    {
        "id": 1,
        "number": "Perda No. 3 Tahun 2024",
        "title": "Pengelolaan dan Perlindungan Hutan Adat di Wilayah Kabupaten Jayapura",
        "category": "adat-budaya",
        "year": 2024,
        "date": "12 Maret 2024",
        "status": "berlaku",
        "type": "Perda",
        "summary": "Mengatur pengakuan, perlindungan, dan pengelolaan hutan adat oleh masyarakat hukum adat di Kabupaten Jayapura. Peraturan ini memuat mekanisme pemetaan wilayah adat, pembentukan lembaga pengelola, dan sanksi bagi pelanggaran.",
        "detail": "Peraturan Daerah ini lahir dari kebutuhan mendesak untuk melindungi hutan adat yang terancam konversi lahan. Perda ini mewajibkan setiap kampung untuk mendaftarkan wilayah hutan adatnya dalam peta resmi kabupaten, memberikan hak pengelolaan eksklusif kepada masyarakat adat setempat, serta melarang eksploitasi oleh pihak luar tanpa persetujuan adat yang terdokumentasi.",
        "document_url": "#",
    },
    {
        "id": 2,
        "number": "Perbup No. 11 Tahun 2024",
        "title": "Pemberian Beasiswa Pendidikan Tinggi bagi Putra-Putri Asli Papua Kabupaten Jayapura",
        "category": "pendidikan",
        "year": 2024,
        "date": "5 Februari 2024",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Menetapkan kriteria, mekanisme seleksi, dan besaran beasiswa pendidikan S1 dan S2 bagi warga asli Papua Kabupaten Jayapura. Mencakup 200 kuota per tahun dengan prioritas jurusan kesehatan, teknik, dan pendidikan.",
        "detail": "Peraturan Bupati ini merupakan revisi dari Perbup 2021, dengan penambahan kuota dan perluasan cakupan ke jenjang S2. Beasiswa mencakup biaya kuliah, biaya hidup, dan biaya buku. Penerima wajib menandatangani perjanjian pengabdian di Kabupaten Jayapura minimal 3 tahun setelah lulus.",
        "document_url": "#",
    },
    {
        "id": 3,
        "number": "SK Bupati No. 445/2024",
        "title": "Penetapan Puskesmas Keliling di 8 Kampung Terpencil Distrik Airu dan Kaureh",
        "category": "kesehatan",
        "year": 2024,
        "date": "18 April 2024",
        "status": "berlaku",
        "type": "SK Bupati",
        "summary": "Menetapkan jadwal dan rute operasional puskesmas keliling untuk 8 kampung terpencil yang tidak memiliki akses jalan darat. Layanan meliputi pemeriksaan umum, imunisasi, dan distribusi obat-obatan dasar setiap dua minggu.",
        "detail": "SK ini merespons temuan bahwa 8 kampung di Distrik Airu dan Kaureh belum terjangkau layanan kesehatan rutin. Tim puskesmas keliling terdiri dari 1 dokter, 2 perawat, dan 1 bidan, menggunakan transportasi perahu motor dan helikopter untuk kampung yang tidak dapat dijangkau jalur air.",
        "document_url": "#",
    },
    {
        "id": 4,
        "number": "Perda No. 7 Tahun 2023",
        "title": "Rencana Tata Ruang Wilayah (RTRW) Kabupaten Jayapura 2023–2043",
        "category": "tata-ruang",
        "year": 2023,
        "date": "20 November 2023",
        "status": "berlaku",
        "type": "Perda",
        "summary": "Menetapkan pola dan struktur ruang Kabupaten Jayapura untuk 20 tahun ke depan, meliputi kawasan lindung, kawasan budidaya, infrastruktur strategis, dan kawasan pengembangan ekonomi di pesisir Teluk Yotefa.",
        "detail": "RTRW ini merupakan pembaruan dari RTRW 2013 dan mengakomodasi pertumbuhan Kota Sentani sebagai pusat pelayanan utama, pengembangan Pelabuhan Depapre, serta perlindungan DAS Memberamo. Dokumen setebal 312 halaman ini menjadi acuan seluruh perizinan dan pembangunan di kabupaten.",
        "document_url": "#",
    },
    {
        "id": 5,
        "number": "Perbup No. 22 Tahun 2023",
        "title": "Standar Pelayanan Minimal Jalan Kampung dan Jembatan Desa di Kabupaten Jayapura",
        "category": "infrastruktur",
        "year": 2023,
        "date": "7 Agustus 2023",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Menetapkan standar kondisi minimum jalan kampung dan jembatan yang harus dipenuhi oleh setiap distrik. Mengatur mekanisme pelaporan kerusakan dan respons perbaikan dengan target waktu tanggap.",
        "detail": "Perbup ini lahir dari banyaknya keluhan warga soal jalan kampung yang rusak parah di musim hujan. Setiap distrik wajib membuat peta kondisi jalan tahunan, dan Dana Desa minimal 30% harus dialokasikan untuk pemeliharaan infrastruktur jalan.",
        "document_url": "#",
    },
    {
        "id": 6,
        "number": "SK Bupati No. 521/2023",
        "title": "Pembentukan Tim Percepatan Pengembangan UMKM Produk Unggulan Kabupaten Jayapura",
        "category": "ekonomi-umkm",
        "year": 2023,
        "date": "3 Mei 2023",
        "status": "berlaku",
        "type": "SK Bupati",
        "summary": "Membentuk tim lintas dinas untuk mengidentifikasi, membina, dan mempromosikan produk UMKM unggulan daerah. Target: 50 UMKM naik kelas per tahun melalui pelatihan, sertifikasi, dan akses pasar digital.",
        "detail": "Tim terdiri dari Dinas Koperasi, Dinas Perindustrian, Dinas Perdagangan, dan perwakilan asosiasi pengusaha lokal. Program kerja mencakup pelatihan, fasilitasi sertifikasi halal dan PIRT, serta akses ke platform e-commerce nasional.",
        "document_url": "#",
    },
    {
        "id": 7,
        "number": "Perda No. 2 Tahun 2023",
        "title": "Perlindungan dan Pengelolaan Lingkungan Hidup Berbasis Kearifan Lokal",
        "category": "lingkungan-hidup",
        "year": 2023,
        "date": "15 Februari 2023",
        "status": "berlaku",
        "type": "Perda",
        "summary": "Mengintegrasikan nilai-nilai kearifan lokal masyarakat adat dalam sistem perlindungan lingkungan hidup. Mengakui sasi (larangan adat) sebagai instrumen pengelolaan sumber daya alam yang sah secara hukum daerah.",
        "detail": "Perda ini merupakan yang pertama di Papua yang secara eksplisit mengakui sasi sebagai mekanisme perlindungan lingkungan. Pelanggaran sasi kini dapat diproses secara administratif melalui jalur hukum daerah. Perda juga mengatur izin lingkungan untuk kegiatan skala kecil di wilayah adat.",
        "document_url": "#",
    },
    {
        "id": 8,
        "number": "Perbup No. 5 Tahun 2022",
        "title": "Pengembangan Destinasi Wisata Alam Danau Sentani Berbasis Komunitas",
        "category": "pariwisata",
        "year": 2022,
        "date": "10 Maret 2022",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Menetapkan zonasi wisata Danau Sentani, standar pelayanan homestay komunitas, dan tata cara perizinan usaha wisata oleh masyarakat lokal. Melarang pembangunan hotel di zona lindung danau.",
        "detail": "Zona I (inti) dilindungi penuh; Zona II (penyangga) hanya untuk wisata non-motorized; Zona III (pemanfaatan) dapat dikembangkan dengan izin. Komunitas lokal diberi hak prioritas untuk usaha wisata di semua zona.",
        "document_url": "#",
    },
    {
        "id": 9,
        "number": "Perbup No. 18 Tahun 2022",
        "title": "Program Ketahanan Pangan dan Pengembangan Pertanian Organik Kabupaten Jayapura",
        "category": "pertanian-perikanan",
        "year": 2022,
        "date": "9 Juli 2022",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Menetapkan target produksi pangan lokal, program subsidi bibit dan pupuk organik, serta pembentukan Kelompok Tani Organik di setiap distrik. Menargetkan swasembada sayur dan umbi-umbian dalam 5 tahun.",
        "detail": "Program berfokus pada 5 komoditas unggulan: singkong, ubi jalar, sayuran dataran tinggi, sagu, dan ikan air tawar. Setiap kelompok tani mendapat pendampingan teknis dari Dinas Pertanian selama 2 tahun pertama.",
        "document_url": "#",
    },
    {
        "id": 10,
        "number": "Perda No. 4 Tahun 2022",
        "title": "Pemberdayaan dan Perlindungan Perempuan serta Anak di Kabupaten Jayapura",
        "category": "hukum-peraturan",
        "year": 2022,
        "date": "28 September 2022",
        "status": "berlaku",
        "type": "Perda",
        "summary": "Menetapkan sistem perlindungan terpadu bagi perempuan dan anak, termasuk pembentukan Pusat Pelayanan Terpadu (PPT) di setiap distrik, mekanisme pelaporan kekerasan, dan program pemberdayaan ekonomi perempuan adat.",
        "detail": "Perda ini mencakup 48 pasal yang mengatur pencegahan kekerasan, penanganan korban, rehabilitasi, dan reintegrasi. PPT di setiap distrik berfungsi sebagai one-stop service. Anggaran minimal 2% dari APBD wajib dialokasikan untuk program ini.",
        "document_url": "#",
    },
    {
        "id": 11,
        "number": "SK Bupati No. 188/2022",
        "title": "Penetapan Upah Minimum Kabupaten (UMK) Jayapura Tahun 2022",
        "category": "ekonomi-umkm",
        "year": 2022,
        "date": "20 November 2022",
        "status": "direvisi",
        "type": "SK Bupati",
        "summary": "Menetapkan Upah Minimum Kabupaten Jayapura sebesar Rp 3.561.932 per bulan untuk tahun 2022, naik 1,09% dari UMK 2021. SK ini kemudian direvisi dengan UMK 2023.",
        "detail": "UMK ini berlaku untuk seluruh pekerja/buruh yang bekerja di wilayah Kabupaten Jayapura, kecuali usaha mikro dan kecil yang menggunakan struktur upah berbasis kesepakatan.",
        "document_url": "#",
    },
    {
        "id": 12,
        "number": "Perda No. 1 Tahun 2021",
        "title": "Penyelenggaraan Pendidikan Berbasis Budaya Lokal di Satuan Pendidikan Dasar",
        "category": "pendidikan",
        "year": 2021,
        "date": "14 Juni 2021",
        "status": "berlaku",
        "type": "Perda",
        "summary": "Mewajibkan muatan lokal budaya Papua dalam kurikulum SD dan SMP, termasuk bahasa daerah, kesenian tradisional, dan pengetahuan ekologi lokal. Minimal 2 jam pelajaran per minggu.",
        "detail": "Dinas Pendidikan diwajibkan menyusun bahan ajar muatan lokal bersama tokoh adat dalam 2 tahun sejak pengesahan. Guru muatan lokal dapat direkrut dari masyarakat adat tanpa mensyaratkan ijazah S1 pendidikan.",
        "document_url": "#",
    },
    {
        "id": 13,
        "number": "Perda No. 2 Tahun 2024",
        "title": "Pertanggungjawaban Pelaksanaan APBD Tahun Anggaran 2023",
        "category": "hukum-peraturan",
        "year": 2024,
        "date": "30 Juli 2024",
        "status": "berlaku",
        "type": "Perda",
        "summary": "Menetapkan laporan realisasi APBD Tahun Anggaran 2023 sebagai bentuk akuntabilitas pemerintah daerah.",
        "detail": "Dokumen ini berisi laporan keuangan pemerintah daerah yang telah diaudit dan menjadi dasar evaluasi fiskal daerah.",
        "document_url": "https://peraturan.bpk.go.id/Details/338593",
    },
    {
        "id": 14,
        "number": "Perbup No. 25 Tahun 2024",
        "title": "Perubahan Penjabaran APBD Tahun Anggaran 2024",
        "category": "hukum-peraturan",
        "year": 2024,
        "date": "15 September 2024",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Mengatur perubahan alokasi anggaran pada APBD 2024.",
        "detail": "Perubahan dilakukan untuk menyesuaikan kebutuhan pembangunan daerah dan kondisi fiskal.",
        "document_url": "https://peraturan.bpk.go.id/Details/336693",
    },
    {
        "id": 15,
        "number": "Perbup No. 31 Tahun 2024",
        "title": "Perubahan Kedua atas Penjabaran APBD Tahun Anggaran 2024",
        "category": "hukum-peraturan",
        "year": 2024,
        "date": "10 Desember 2024",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Penyesuaian lanjutan APBD 2024.",
        "detail": "Digunakan untuk optimalisasi anggaran di akhir tahun.",
        "document_url": "https://peraturan.bpk.go.id/Details/338598",
    },
    {
        "id": 16,
        "number": "Perda No. 1 Tahun 2025",
        "title": "Rencana Tata Ruang Wilayah (RTRW) Kabupaten Jayapura",
        "category": "tata-ruang",
        "year": 2025,
        "date": "18 Februari 2025",
        "status": "berlaku",
        "type": "Perda",
        "summary": "Pedoman tata ruang wilayah Kabupaten Jayapura.",
        "detail": "Mengatur zonasi kawasan lindung, budidaya, dan pengembangan wilayah strategis.",
        "document_url": "https://jayapurakab.go.id/rtrw-kab-jayapura-2025/",
    },
    {
        "id": 17,
        "number": "Perbup No. 28 Tahun 2025",
        "title": "Standar Harga Satuan Pemerintah Kabupaten Jayapura",
        "category": "hukum-peraturan",
        "year": 2025,
        "date": "12 Juni 2025",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Standar harga barang dan jasa pemerintah daerah.",
        "detail": "Digunakan sebagai acuan dalam penyusunan anggaran OPD.",
        "document_url": "https://jayapurakab.go.id/perbub-nomor-28-tahun-2025-tentang-standar-harga-satuan/",
    },
    {
        "id": 18,
        "number": "Perbup No. 31 Tahun 2025",
        "title": "Analisis Standar Belanja Konstruksi",
        "category": "infrastruktur",
        "year": 2025,
        "date": "20 Agustus 2025",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Standar biaya proyek konstruksi daerah.",
        "detail": "Menjadi acuan perencanaan dan penganggaran proyek fisik.",
        "document_url": "https://jayapurakab.go.id/category/peraturan-bupati/",
    },
    {
        "id": 19,
        "number": "Perbup No. 33 Tahun 2025",
        "title": "Standar Biaya Umum Pemerintah Daerah",
        "category": "hukum-peraturan",
        "year": 2025,
        "date": "5 Oktober 2025",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Standar biaya operasional pemerintah.",
        "detail": "Mengatur perjalanan dinas, honorarium, dan kegiatan operasional.",
        "document_url": "https://jayapurakab.go.id/category/peraturan-bupati/",
    },
    {
        "id": 20,
        "number": "Perbup No. 29 Tahun 2026",
        "title": "Harga Satuan Pokok Kegiatan Tahun Anggaran 2026",
        "category": "hukum-peraturan",
        "year": 2026,
        "date": "10 Januari 2026",
        "status": "berlaku",
        "type": "Perbup",
        "summary": "Harga satuan kegiatan untuk tahun anggaran 2026.",
        "detail": "Digunakan dalam seluruh proses perencanaan anggaran daerah.",
        "document_url": "https://jayapurakab.go.id/category/peraturan-bupati/",
    },
]

STATS = {
    "id": 1,
    "kecamatan": 19,
    "kampung": 139,
    "kebijakan_terdokumentasi": 384,
    "warga_berlangganan": 4820,
    "tahun_data": "2018–2024",
}


def seed_db() -> None:
    db = SessionLocal()
    try:
        if db.query(Category).count() == 0:
            db.add_all([Category(**c) for c in CATEGORIES])

        if db.query(Policy).count() == 0:
            db.add_all([Policy(**p) for p in POLICIES])

        if db.query(Stats).count() == 0:
            db.add(Stats(**STATS))

        db.commit()
    finally:
        db.close()
